dist: trusty
sudo: false
language: cpp
matrix:
    include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
script:
    - cmake tests
    - cmake --build .
    - ./run_tests
