dist: trusty
sudo: false
language: cpp
matrix:
    include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang-10"
script:
    - cmake tests
    - cmake --build .
    - ./run_tests
